const clothesList = [
    {
      "id": 1,
      "nombreProducto": "Camiseta Deportiva",
      "descripcion": "Camiseta de algodón de manga corta Nike",
      "categoria": "Camisetas",
      "precio": 15.99,
      "tallasDisponibles": ["S", "M", "L", "XL"],
      "coloresDisponibles": ["Blanco", "Negro", "Gris", "Azul"],
      "material": "Algodón",
      "imagen": "assets/clothes-man/img_man1.png",
      "cantidadEnStock": 28,
      "identificador": "MAN"
    },
    {
      "id": 2,
      "nombreProducto": "Pantalones",
      "descripcion": "Pantalones holgados de estilo deportivo",
      "categoria": "Pantalones",
      "precio": 29.99,
      "tallasDisponibles": ["28", "30", "32", "34"],
      "coloresDisponibles": ["Azul oscuro", "Azul claro", "Negro"],
      "material": "Denim",
      "imagen": "assets/clothes-man/img_man2.png",
      "cantidadEnStock": 40,
      "identificador": "MAN"
    },
    {
      "id": 3,
      "nombreProducto": "Camisa Wear",
      "descripcion": "Easy Wear celeste manga corta para dama",
      "categoria": "Blusas",
      "precio": 39.99,
      "tallasDisponibles": ["S", "M", "L", "XL"],
      "coloresDisponibles": ["Blanco", "Negro", "Gris", "Azul"],
      "material": "Lana",
      "imagen": "assets/clothes-women/img_women1.png",
      "cantidadEnStock": 23,
      "identificador": "WOMAN"
    },
    {
      "id": 4,
      "nombreProducto": "Vestido Mini",
      "descripcion": "mini vestido sin espalda damas costumbre sin tirantes",
      "categoria": "Vestidos",
      "precio": 39.99,
      "tallasDisponibles": ["S", "M", "L", "XL"],
      "coloresDisponibles": ["Blanco", "Negro", "Gris", "Azul"],
      "material": "Lana",
      "imagen": "assets/clothes-women/img_women2.png",
      "cantidadEnStock": 21,
      "identificador": "WOMAN"
    },
    {
      "id": 5,
      "nombreProducto": "Camisa manga larga de color",
      "descripcion": "Camisa de algodon Manga Larga De Color Solido",
      "categoria": "Camisas Formales",
      "precio": 67.65,
      "tallasDisponibles": ["S", "M", "L", "XL"],
      "coloresDisponibles": ["Blanco", "Negro", "Gris", "Azul"],
      "material": "Algodón",
      "imagen": "assets/clothes-boy/img_boy1.png",
      "cantidadEnStock": 3,
      "identificador": "KIDS"
    },
    {
      "id": 6,
      "nombreProducto": "Camisa manga larga casual cuadriculada",
      "descripcion": "Camisa de vestir casual manga larga cuadriculada ",
      "categoria": "Camisas Formales",
      "precio": 67.65,
      "tallasDisponibles": ["S"],
      "coloresDisponibles": ["Rojo"],
      "material": "Algodón",
      "imagen": "assets/clothes-boy/img_boy2.png",
      "cantidadEnStock": 5,
      "identificador": "KIDS"
    },
    {
      "id": 7,
      "nombreProducto": "Pijama de superheroe de los Vengadores",
      "descripcion": "Pijama completa de tus superheroes favoritos",
      "categoria": "Pijama",
      "precio": 30.25,
      "tallasDisponibles": ["S"],
      "coloresDisponibles": ["Capitan America, IronMan, Hulk, Batman"],
      "material": "Algodón",
      "imagen": "assets/clothes-boy/img_boy3.png",
      "cantidadEnStock": 3,
      "identificador": "KIDS"
    },
    {
      "id": 8,
      "nombreProducto": "Zapatillas de Paw Patrol para niños",
      "descripcion": "Zapatillas super comodas con diseño de PawPatrol",
      "categoria": "Zapatos",
      "precio": 25.99,
      "tallasDisponibles": ["S"],
      "coloresDisponibles": ["Blanco"],
      "material": "Cuerina",
      "imagen": "assets/clothes-boy/img_boy4.png",
      "cantidadEnStock": 10,
      "identificador": "KIDS"
      },
      {
          "id": 9,
          "nombreProducto": "Blusa Crop Top",
          "descripcion": "Top manga larga negro",
          "categoria": "Blusa",
          "precio": 10.00,
          "tallasDisponibles": ["S, M, L, XL"],
          "coloresDisponibles": ["Negro"],
          "material": "Satín",
          "imagen": "assets/clothes-women/BlusaNegra.jpg",
          "cantidadEnStock": 10,
          "identificador": "WOMAN"
      },
      {
          "id": 10,
          "nombreProducto": "Corsé Tejido",
          "descripcion": "Blusa tipo corsé tejido blanco de tirantes",
          "categoria": "Blusa",
          "precio": 12.50,
          "tallasDisponibles": ["S, M, L, XL"],
          "coloresDisponibles": ["Blanco"],
          "material": "Lana de algodón",
          "imagen": "assets/clothes-women/corse.jpg",
          "cantidadEnStock": 6,
          "identificador": "WOMAN"
      },
       {
          "id": 11,
          "nombreProducto": "Crop Top Tejido",
          "descripcion": "Crop top tejido verde manga larga",
          "categoria": "Sueter",
          "precio": 15.00,
          "tallasDisponibles": ["S, M, L, XL"],
          "coloresDisponibles": ["Verde"],
          "material": "Lana de algodón",
          "imagen": "assets/clothes-women/Sueter.jpg",
          "cantidadEnStock": 15,
          "identificador": "WOMAN"
      },
      {
          "id": 12,
          "nombreProducto": "Tank Top",
          "descripcion": "Top sin mangas blanco",
          "categoria": "Blusa",
          "precio": 12.50,
          "tallasDisponibles": ["S, M, L, XL"],
          "coloresDisponibles": ["Blanco"],
          "material": "Algodón",
          "imagen": "assets/clothes-women/Tanktop.jpg",
          "cantidadEnStock": 10,
          "identificador": "WOMAN"
      },
      {
        "id": 13,
        "nombreProducto": "Bata de baño para niña",
        "descripcion": "Bata de baño multicolor con estampado para niña",
        "categoria": "Bata de baño",
        "precio": 31.90,
        "tallasDisponibles": ["M"],
        "coloresDisponibles": ["Multicolor"],
        "material": "Algodón",
        "imagen": "assets/clothes-girl/img_girl1.png",
        "cantidadEnStock": 5,
        "identificador": "GIRL"
      },
      {
        "id": 14,
        "nombreProducto": "Blusa de Snoopy para niña",
        "descripcion": "Blusa negra con estampado de Snoopy para niña",
        "categoria": "Blusa",
        "precio": 15.95,
        "tallasDisponibles": ["M"],
        "coloresDisponibles": ["Negro"],
        "material": "Algodón",
        "imagen": "assets/clothes-girl/img_girl2.png",
        "cantidadEnStock": 20,
        "identificador": "GIRL"
      },
      {
        "id": 15,
        "nombreProducto": "Vestido con estampado para niña",
        "descripcion": "Vestido multicolor con estampado para niña",
        "categoria": "Vestido",
        "precio": 25.90,
        "tallasDisponibles": ["S"],
        "coloresDisponibles": ["Multicolor"],
        "material": "Algodón",
        "imagen": "assets/clothes-girl/img_girl3.png",
        "cantidadEnStock": 15,
        "identificador": "GIRL"
      },
      {
        "id": 16,
        "nombreProducto": "Jeans Levi´s para niña",
        "descripcion": "Jeans Levi´s 720 negro lavado para niña",
        "categoria": "Jeans",
        "precio": 39.90,
        "tallasDisponibles": ["M"],
        "coloresDisponibles": ["Negro"],
        "material": "Algodón",
        "imagen": "assets/clothes-girl/img_girl4.png",
        "cantidadEnStock": 5,
        "identificador": "GIRL"
      },  
      {
        "id": 17,
        "nombreProducto": "Camisa lisa de vestir",
        "descripcion": "Camisa lisa de vestir color durazno",
        "categoria": "Camisas",
        "precio": 49.90,
        "tallasDisponibles": ["M"],
        "coloresDisponibles": ["Durazno"],
        "material": "Algodón",
        "imagen": "assets/clothes-man/img_man3.jpg",
        "cantidadEnStock": 5,
        "identificador": "MAN"
      },
      {
        "id": 18,
        "nombreProducto": "Blazar negro",
        "descripcion": "Blazer 100% algodon",
        "categoria": "Blazers",
        "precio": 89.90,
        "tallasDisponibles": ["L"],
        "coloresDisponibles": ["Negro"],
        "material": "Algodón",
        "imagen": "assets/clothes-man/img_man4.jpg",
        "cantidadEnStock": 5,
        "identificador": "MAN"
      },
      {
        "id": 19,
        "nombreProducto": "Sueter invierno",
        "descripcion": "Sueter invierno celeste",
        "categoria": "Chaquetas",
        "precio": 79.90,
        "tallasDisponibles": ["M"],
        "coloresDisponibles": ["Celeste"],
        "material": "Algodón",
        "imagen": "assets/clothes-man/img_man5.jpg",
        "cantidadEnStock": 5,
        "identificador": "MAN"
      },
      {
        "id": 20,
        "nombreProducto": "Corbata lino",
        "descripcion": "Corbata amarillo con rayas",
        "categoria": "Corbatas",
        "precio": 59.90,
        "tallasDisponibles": ["M"],
        "coloresDisponibles": ["Amarillo"],
        "material": "Lino",
        "imagen": "assets/clothes-man/img_man6.jpg",
        "cantidadEnStock": 5,
        "identificador": "MAN"
      },
      {
        "id": 21,
        "nombreProducto": "Camisa oversize",
        "descripcion": "Camisa oversize blanca",
        "categoria": "Camisas",
        "precio": 39.90,
        "tallasDisponibles": ["XL"],
        "coloresDisponibles": ["Blanco"],
        "material": "Algodón",
        "imagen": "assets/clothes-man/img_man7.jpg",
        "cantidadEnStock": 5,
        "identificador": "MAN"
      },
  ]

  export { clothesList };